# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('score', models.IntegerField(default=0)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('tag', models.CharField(blank=True, max_length=16)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
