# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicegame', '0002_auto_20170228_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='num',
            field=models.BooleanField(default=False),
        ),
    ]
